blank_issues_enabled: true
contact_links:
  - name: 📜 About - see the SSW Rule - Do you have the best GitHub issue template?
    url: https://www.ssw.com.au/rules/do-you-have-the-best-github-issue-template
    about: See our rule on GitHub issue templates
  - name: Contact Us
    url: https://www.ssw.com.au/ssw/Company/ContactUs.aspx
    about: Contact us for all your consulting needs!