blank_issues_enabled: true
contact_links:
  - name: 📜 About this page - see the ssw rule Do you have the best GitHub issue template?
    url: https://www.ssw.com.au/rules/do-you-have-the-best-github-issue-template
    about: See our rule on GitHub issue templates